

all:
	@echo "Compilación y ejecución de la práctica"
	python ClienteServidorFIFOsFichero.py  
cli3:
	@echo "Cliente"
	python3 cli3.py
serv3:
	@echo "Servidor"
	python3 serv3.py
clean:
	@echo "Limpiando..."
